name: OBIS manual
title: OBIS manual
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: false
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme